name: HelloWorld
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues. 
on: [push] # anybody push in this, it will trigger
jobs: # pipeline. One workflow will have multiple pipeline
  hello: # job name 
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hello World"
      - name: step-2
        run: echo "Hello GitHub Action"