# search in google as "github actions" --> Get started with actions --> How-tos --> write-workflows --> choose-when-workflows-run --> control-workflow-concurrency
name: concurrency
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues. 
on: [push] # anybody push in this, it will trigger
concurrency:
  # this workflow should be triggered for any branch only once
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true #Existing will be cancelled and latest will run (because it will take latest commit)
jobs: # pipeline. One workflow will have multiple pipeline
  hello: # job name 
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: sleep 20
      