# search in google as "github actions" --> Get started with actions --> reference --> workflows-and-actions --> workflow-syntax --> jobsjob_idneeds
name: Dependency
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues. 
on: [push] # anybody push in this, it will trigger
jobs: # pipeline. One workflow will have multiple pipeline
  job-1: # name of the job
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hii, I am from job-1"
  
  job-2: # name of the job
    needs: job-1 # job-2 is dependent on job-1
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hii, I am from job-2"
  
  job-3: # name of the job
    needs: job-2 # job-3 is dependent on job-2
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hii, I am from job-3"

  job-4: # name of the job
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hii, I am from job-4"

# job-1, job-2, job-3 run in sequential manner, job-1 and job-2 run in parallel manner because of no dependency