# search in google as "github actions marketplace" --> marketplace --> search as "checkout" --> click on checkout --> - uses: actions/checkout@v6
name: checkout-code
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues. 
on: [push] # anybody push in this, it will trigger
jobs: # pipeline. One workflow will have multiple pipeline
  build: # name of the job
    runs-on: ubuntu-latest # where to run # linux os
    steps: # like stages in jenkins
    # checkout will happen here
      - name: checkout
        uses: actions/checkout@v6

      - name: display the files
        uses: ls -la

 