# search in google as "github actions" --> Get started with actions --> concepts --> workflows and actions --> workflows --> scroll down --> click on "creating on example workflow" 
name: self-hosted-runner
# When to trigger this pipeline. We can trigger on push or manual or someother events like creating PR, updating PR, creating branches, creating issues. 
on: [push] # anybody push in this, it will trigger
jobs: # pipeline. One workflow will have multiple pipeline
  hello: # job name 
    runs-on: self-hosted # give any label metioned in (after 1st command of congigure and 3rd prompt)
    steps: # like stages in jenkins
      - name: step-1
        run: echo "Hello World"
      - name: step-2
        run: echo "Hello GitHub Action"